apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  namespace: web
  labels:
    app: tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registrympx1704.azurecr.io/tripviewer:1.0
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: USERPROFILE_API_ENDPOINT
            value: "http://userprofile-service.api.svc.cluster.local:80"
          - name: TRIPS_API_ENDPOINT
            value: "http://trips-service.api.svc.cluster.local:80"
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
  namespace: web
spec:
  selector:
    app: tripviewer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

