# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: e393d4d7-693e-43bb-8c53-9ebf6d6426d9   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: ohteam1keyvault        # Set to the name of your key vault
    objects: |
      array:
        - |
          objectName: SQL-USER
          objectType: secret              # object types: secret, key, or cert
        - |
          objectName: SQL-PASSWORD
          objectType: secret
        - |
          objectName: SQL-SERVER
          objectType: secret
        - |
          objectName: SQL-DBNAME
          objectType: secret
    tenantId: 43328483-280a-42f9-b3dd-160c78474c2e
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: e393d4d7-693e-43bb-8c53-9ebf6d6426d9
  provider: azure
  secretObjects:
  - data:
    - key: SQL_DBNAME
      objectName: SQL-DBNAME
    - key: SQL_SERVER
      objectName: SQL-SERVER
    - key: SQL_PASSWORD
      objectName: SQL-PASSWORD
    - key: SQL_USER
      objectName: SQL-USER
    secretName: environmentsecrets
    type: Opaque
