# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: e393d4d7-693e-43bb-8c53-9ebf6d6426d9   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: ohteam1keyvault        # Set to the name of your key vault
    objects:  |
      array:
        - |
          objectName: SQL-USER
          objectType: secret              # object types: secret, key, or cert
          objectAlias: SQL_USER
          secretName: SQL_USER
        - |
          objectName: SQL-PASSWORD
          objectType: secret
          objectAlias: SQL_PASSWORD
          secretName: SQL_PASSWORD
        - |
          objectName: SQL-SERVER
          objectType: secret
          objectAlias: SQL_SERVER
          secretName: SQL_SERVER
        - |
          objectName: SQL-DBNAME
          objectType: secret
          objectAlias: SQL_DBNAME
          secretName: SQL_DBNAME
    tenantId: 43328483-280a-42f9-b3dd-160c78474c2e                 # The tenant ID of the key vault